##
## Copyright (c) 2021, NVIDIA CORPORATION.  All rights reserved.
##
## NVIDIA CORPORATION and its licensors retain all intellectual property
## and proprietary rights in and to this software, related documentation
## and any modifications thereto.  Any use, reproduction, disclosure or
## distribution of this software and related documentation without an express
## license agreement from NVIDIA CORPORATION is strictly prohibited.
##
pages:
  image: gitlab-master.nvidia.com:5005/hwinf-scm/pages-runner
  stage: deploy
  script:
  - mv docs public 
  - echo 'Done.'  
  tags:
  - pages
  artifacts:
    paths:
    - public
  only:
  - documentation
